### ISSUE TITLE
RichRecordConverter don't show filename and line on error logs

### ISSUE THREAD

**Issue by pablorsk** [marvinlabs/laravel-discord-logger#22]
Hi!

RichRecordConverter show all trace, but filename and line with error is missing (the most important information).

**Actual behaviour**

```
[2021-12-16 18:31:07] production.ERROR
Call to undefined method App\Model::badMethod()

Stacktrace
`#0 /app/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\Database\Eloquent\Model::throwBadMethodCallException()
#1 /app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1993): Illuminate\Database\Eloquent\Model->forwardCallTo()
...
```

**Spected behaviour**

(line `On /app/Model.php(115)` added)

```
[2021-12-16 18:31:07] production.ERROR
Call to undefined method App\Model::badMethod()
On /app/Model.php(115) 

Stacktrace
`#0 /app/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\Database\Eloquent\Model::throwBadMethodCallException()
#1 /app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1993): Illuminate\Database\Eloquent\Model->forwardCallTo()
...
```

![image](https://user-images.githubusercontent.com/938894/146453186-6078d698-ba4f-4a13-adff-2117fd7e3a1f.png)

**Comment by vpratfr** [comment]
Do you think you could submit a pr?

**Comment by vpratfr** [comment]
Thanks. I have tagged that as 1.1.8.
